# Generated by Django 5.0.2 on 2024-03-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
