# Generated by Django 5.0.2 on 2024-03-05 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0002_article_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
