# Generated by Django 5.0.2 on 2024-03-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0009_category_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_1', models.ImageField(blank=True, null=True, upload_to='dimg')),
                ('logo_2', models.ImageField(blank=True, null=True, upload_to='dimg')),
                ('title', models.CharField(max_length=255)),
                ('title_tr', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255)),
                ('description_tr', models.CharField(max_length=255, null=True)),
                ('description_en', models.CharField(max_length=255, null=True)),
                ('keywords', models.CharField(max_length=255)),
                ('keywords_tr', models.CharField(max_length=255, null=True)),
                ('keywords_en', models.CharField(max_length=255, null=True)),
                ('phone_fixed', models.CharField(max_length=15)),
                ('phone_mobile', models.CharField(max_length=15)),
                ('fax', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=10)),
                ('facebook_url', models.URLField(max_length=255)),
                ('twitter_url', models.URLField(max_length=255)),
                ('instagram_url', models.URLField(max_length=255)),
                ('youtube_url', models.URLField(max_length=255)),
            ],
        ),
    ]
